### ISSUE TITLE
终于找到这种流程图了  公司要求这种样式 写的头都大了 谢谢大佬 给你个 星

### ISSUE THREAD

**Issue by liubaodong** [wertsafc123/tree#2]

**Comment by wertsafc123** [comment]
不不不我不是大佬，能帮上忙就好

**Comment by liubaodong** [comment]
我可以加你好友吗 向你学习 交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wertsafc123"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 下午5:25
收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 
抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wertsafc123/tree] 终于找到这种流程图了  公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2)




不不不我不是大佬，能帮上忙就好

**Comment by wertsafc123** [comment]
> 我可以加你好友吗向你学习交流
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:25 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 不不不我不是大佬，能帮上忙就好 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个很简单的，你看完就懂了

**Comment by liubaodong** [comment]
好的 谢谢啦 以后又不懂得 问你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wertsafc123"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 下午5:32
收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 
抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wertsafc123/tree] 终于找到这种流程图了  公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2)



 
我可以加你好友吗向你学习交流
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:25 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 不不不我不是大佬，能帮上忙就好 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
这个很简单的，你看完就懂了

**Comment by wertsafc123** [comment]
> 好的 谢谢啦 以后又不懂得 问你
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:32 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 我可以加你好友吗向你学习交流 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:25 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 不不不我不是大佬，能帮上忙就好 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 这个很简单的，你看完就懂了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

客气

**Comment by liubaodong** [comment]
您好 有一个 小 bug&nbsp; 在选择条件 删除之后 会留下两个 添加按钮&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wertsafc123"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 下午5:35
收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 
抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wertsafc123/tree] 终于找到这种流程图了  公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2)



 
好的 谢谢啦 以后又不懂得 问你
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:32 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 我可以加你好友吗向你学习交流 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wertsafc123"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 下午5:25 收件人: "wertsafc123/tree"<tree@noreply.github.com&gt;; 抄送: "余生"<2458825436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [wertsafc123/tree] 终于找到这种流程图了 公司要求这种样式 写的头都大了 谢谢大佬 给你个 星 (#2) 不不不我不是大佬，能帮上忙就好 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 这个很简单的，你看完就懂了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
客气
